let predefinedSkills = [
  "JavaScript",
  "Python",
  "React",
  "Node.js",
  "CSS",
  "HTML",
  "Java",
  "C++",
  "SQL",
  "Ruby",
  "PHP",
  "TypeScript",
  "Swift",
  "Go",
  "Kotlin",
  "Active Listening",
  "Public Speaking",
  "Negotiation",
  "Persuasion",
  "Presentation Skills",
  "Conflict Resolution",
  "Written Communication",
  "Verbal Communication",
  "Interpersonal Skills",
  "Non-verbal Communication",
  "Emotional Intelligence",
  "Report Writing",
  "Storytelling",
  "Feedback Delivery",
  "Interviewing Skills",
  "Assertiveness",
  "Empathy",
  "Customer Service",
  "Cross-cultural Communication",
  "Communication Strategy",
  "Data Analysis",
  "Coding/Programming",
  "Software Development",
  "System Administration",
  "IT Support",
  "Database Management",
  "Network Security",
  "Cloud Computing",
  "Web Development",
  "Data Visualization",
  "Software Engineering",
  "Machine Learning",
  "Artificial Intelligence",
  "Systems Integration",
  "Cybersecurity",
  "Algorithm Design",
  "Technical Writing",
  "Blockchain Technology",
  "Troubleshooting",
  "API Development",
  "Management Skills",
  "Project Management",
  "Team Leadership",
  "Budget Management",
  "Strategic Planning",
  "Risk Management",
  "Performance Evaluation",
  "Change Management",
  "Resource Allocation",
  "Process Improvement",
  "Goal Setting",
  "Time Management",
  "Decision Making",
  "Workflow Optimization",
  "Conflict Management",
  "Stakeholder Management",
  "Organizational Skills",
  "Crisis Management",
  "Team Building",
  "Operational Efficiency",
  "Business Planning",
  "Creative Skills",
  "Graphic Design",
  "Content Creation",
  "Video Production",
  "Photography",
  "Animation",
  "User Experience (UX) Design",
  "User Interface (UI) Design",
  "Copywriting",
  "Branding",
  "Illustration",
  "Creative Writing",
  "Music Production",
  "Visual Merchandising",
  "Art Direction",
  "Web Design",
  "Multimedia Production",
  "Scriptwriting",
  "Social Media Marketing",
  "Creative Strategy",
  "Typography",
  "Analytical Skills",
  "Problem Solving",
  "Critical Thinking",
  "Research Skills",
  "Data Interpretation",
  "Market Analysis",
  "Statistical Analysis",
  "Trend Analysis",
  "Business Analysis",
  "SWOT Analysis",
  "Financial Analysis",
  "Forecasting",
  "Risk Assessment",
  "Decision Support",
  "Competitive Analysis",
  "Process Mapping",
  "Data Mining",
  "Quality Assurance",
  "Benchmarking",
  "Report Generation",
  "Hypothesis Testing",
  "Technical Proficiency",
  "Microsoft Office Suite",
  "CRM Software",
  "ERP Systems",
  "Project Management Tools",
  "Adobe Creative Suite",
  "HTML/CSS",
  "SQL",
  "JavaScript",
  "Python",
  "R Programming",
  "MATLAB",
  "SAP",
  "Salesforce",
  "AutoCAD",
  "GIS Software",
  "Video Editing Software",
  "Content Management Systems (CMS)",
  "E-commerce Platforms",
  "Cloud Storage Solutions",
  "Networking Tools",
  "Customer Service Skills",
  "Client Relations",
  "Complaint Resolution",
  "Service Orientation",
  "Product Knowledge",
  "Follow-up",
  "Upselling",
  "Customer Retention",
  "Help Desk Support",
  "Service Recovery",
  "Service Design",
  "Personalized Service",
  "Multichannel Support",
  "Empathy in Service",
  "Order Management",
  "Technical Support",
  "Client Onboarding",
  "Service Excellence",
  "Customer Feedback Management",
  "Inquiry Handling",
  "Support Documentation",
  "Financial Skills",
  "Budgeting",
  "Financial Planning",
  "Accounting",
  "Investment Analysis",
  "Tax Preparation",
  "Financial Reporting",
  "Bookkeeping",
  "Cost Analysis",
  "Asset Management",
  "Cash Flow Management",
  "Credit Analysis",
  "Risk Management",
  "Financial Modeling",
  "Profit and Loss Analysis",
  "Auditing",
  "Payroll Management",
  "Revenue Forecasting",
  "Expense Tracking",
  "Banking Operations",
  "Portfolio Management",
  "Human Resources Skills",
  "Recruitment",
  "Employee Relations",
  "Performance Management",
  "Training and Development",
  "Benefits Administration",
  "HR Policies",
  "Talent Management",
  "Onboarding",
  "Compensation Management",
  "Compliance",
  "Employee Engagement",
  "HRIS Systems",
  "Succession Planning",
  "Conflict Resolution",
  "Workplace Safety",
  "HR Strategy",
  "Diversity and Inclusion",
  "Labor Relations",
  "Workforce Planning",
  "HR Analytics",
  "Sales Skills",
  "Lead Generation",
  "Sales Pitching",
  "Negotiation",
  "Relationship Building",
  "Account Management",
  "Sales Forecasting",
  "Territory Management",
  "Pipeline Management",
  "Sales Strategy",
  "Customer Acquisition",
  "Quota Achievement",
  "Sales Reporting",
  "Product Demonstrations",
  "Competitive Selling",
  "Sales Training",
  "Market Penetration",
  "Deal Closing",
  "Sales Analytics",
  "Consultative Selling",
  "Proposal Writing",
  "Marketing Skills",
  "Market Research",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Brand Management",
  "Advertising",
  "Public Relations",
  "Campaign Management",
  "Market Segmentation",
  "Influencer Marketing",
  "Event Planning",
  "Marketing Strategy",
  "Competitive Intelligence",
  "Media Planning",
  "Promotion Planning",
  "Analytics",
  "Customer Insights",
  "IT Skills",
  "Network Administration",
  "System Installation",
  "Troubleshooting",
  "IT Support",
  "Database Administration",
  "Cybersecurity",
  "Cloud Services",
  "Software Installation",
  "System Integration",
  "Backup and Recovery",
  "Technical Documentation",
  "IT Infrastructure",
  "Systems Analysis",
  "IT Project Management",
  "Security Management",
  "System Upgrades",
  "Software Development Life Cycle (SDLC)",
  "Help Desk Management",
  "IT Compliance",
  "Web Server Management",
  "Legal Skills",
  "Contract Law",
  "Legal Research",
  "Legal Writing",
  "Compliance",
  "Case Management",
  "Intellectual Property",
  "Litigation Support",
  "Regulatory Affairs",
  "Risk Management",
  "Legal Consulting",
  "Dispute Resolution",
  "Estate Planning",
  "Family Law",
  "Employment Law",
  "Real Estate Law",
  "Corporate Law",
  "Legal Drafting",
  "Evidence Handling",
  "Court Procedures",
  "Legal Analysis",
  "Education and Training Skills",
  "Curriculum Development",
  "Lesson Planning",
  "Classroom Management",
  "Educational Assessment",
  "Instructional Design",
  "E-learning Development",
  "Teacher Training",
  "Academic Advising",
  "Student Counseling",
  "Educational Research",
  "Learning Management Systems (LMS)",
  "Tutoring",
  "Educational Technology",
  "Professional Development",
  "Teaching Methodologies",
  "Pedagogy",
  "Educational Policy",
  "Student Engagement",
  "Educational Program Evaluation",
  "Distance Learning",
  "Healthcare Skills",
  "Patient Care",
  "Medical Diagnosis",
  "Clinical Skills",
  "Healthcare Management",
  "Medical Records Management",
  "Medical Research",
  "Pharmacy Knowledge",
  "Health Education",
  "Nursing Skills",
  "Emergency Response",
  "Patient Counseling",
  "Health Informatics",
  "Rehabilitation Services",
  "Infection Control",
  "Health Promotion",
  "Medical Billing",
  "Diagnostic Testing",
  "Care Coordination",
  "Healthcare Policy",
  "Medical Ethics",
  "Engineering Skills",
  "Engineering Design",
  "CAD (Computer-Aided Design)",
  "Systems Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Structural Analysis",
  "Thermodynamics",
  "Fluid Dynamics",
  "Engineering Analysis",
  "Robotics",
  "Process Engineering",
  "Materials Science",
  "Quality Control",
  "Prototyping",
  "Simulation",
  "Engineering Project Management",
  "Maintenance Engineering",
  "Safety Engineering",
  "Production Engineering",
  "Research Skills",
  "Data Collection",
  "Statistical Analysis",
  "Experimental Design",
  "Literature Review",
  "Hypothesis Testing",
  "Field Research",
  "Data Interpretation",
  "Survey Design",
  "Qualitative Analysis",
  "Quantitative Analysis",
  "Research Methodology",
  "Report Writing",
  "Academic Research",
  "Data Management",
  "Grant Writing",
  "Research Ethics",
  "Literature Search",
  "Evidence-Based Research",
  "Research Presentation",
  "Peer Review",
  "Design Skills",
  "Graphic Design",
  "User Experience (UX) Design",
  "User Interface (UI) Design",
  "3D Modeling",
  "Visual Design",
  "Product Design",
  "Industrial Design",
  "Motion Graphics",
  "Typography",
  "Color Theory",
  "Layout Design",
  "Adobe Creative Suite",
  "Sketching",
  "Design Thinking",
  "Design Prototyping",
  "Wireframing",
  "Mockups",
  "Animation",
  "Branding",
  "Creative Suite",
  "Scientific Skills",
  "Laboratory Techniques",
  "Scientific Research",
  "Experimental Procedures",
  "Data Analysis",
  "Scientific Writing",
  "Scientific Theory",
  "Laboratory Safety",
  "Sample Preparation",
  "Data Interpretation",
  "Instrument Calibration",
  "Scientific Method",
  "Research Design",
  "Fieldwork",
  "Statistical Software",
  "Scientific Communication",
  "Chemical Analysis",
  "Biological Research",
  "Environmental Science",
  "Physics Experiments",
  "Medical Research",
  "Logistics and Supply Chain Skills",
  "Inventory Management",
  "Supply Chain Management",
  "Procurement",
  "Logistics Coordination",
  "Warehouse Management",
  "Distribution Planning",
  "Transportation Management",
  "Demand Forecasting",
  "Vendor Management",
  "Supply Chain Optimization",
  "Order Fulfillment",
  "Freight Management",
  "Supplier Relations",
  "Risk Management",
  "Cost Reduction",
  "Supply Chain Analytics",
  "Logistics Strategy",
  "Inventory Control",
  "Shipping and Receiving",
  "Process Improvement",
  "Personal Development Skills",
  "Self-Motivation",
  "Time Management",
  "Stress Management",
  "Goal Setting",
  "Adaptability",
  "Resilience",
  "Critical Thinking",
  "Problem-Solving",
  "Decision Making",
  "Personal Finance",
  "Networking",
  "Confidence Building",
  "Emotional Intelligence",
  "Creativity",
  "Mindfulness",
  "Work-Life Balance",
  "Self-Awareness",
  "Professional Development",
  "Leadership",
  "Conflict Management",
  "Administration Skills",
  "Office Management",
  "Record Keeping",
  "Scheduling",
  "Travel Arrangements",
  "Administrative Support",
  "Meeting Coordination",
  "Document Management",
  "Office Supplies Management",
  "Event Planning",
  "Database Management",
  "Filing Systems",
  "Budget Tracking",
  "Administrative Procedures",
  "Customer Service",
  "Executive Support",
  "Correspondence Management",
  "Report Preparation",
  "Workflow Management",
  "Administrative Coordination",
  "Project Coordination",
  "Customer Relationship Skills",
  "Relationship Management",
  "Customer Feedback Analysis",
  "Loyalty Programs",
  "Client Retention Strategies",
  "Account Management",
  "Customer Engagement",
  "Relationship Building",
  "Client Consultation",
  "Customer Experience Management",
  "Personalized Service",
  "CRM Systems",
  "Service Improvement",
  "Customer Journey Mapping",
  "Relationship Marketing",
  "Client Communication",
  "Service Recovery",
  "Client Satisfaction",
  "Customer Onboarding",
  "Account Development",
  "Client Support",
  "Manufacturing Skills",
  "Production Planning",
  "Quality Control",
  "Process Optimization",
  "Lean Manufacturing",
  "Equipment Maintenance",
  "Production Scheduling",
  "Manufacturing Engineering",
  "Assembly Line Management",
  "Process Improvement",
  "Supply Chain Management",
  "Inventory Control",
  "Product Testing",
  "Safety Standards",
  "Machine Operation",
  "Manufacturing Processes",
  "Cost Reduction",
  "Production Efficiency",
  "Technical Troubleshooting",
  "Industrial Engineering",
  "Facility Management",
  "Automotive Skills",
  "Vehicle Maintenance",
  "Automotive Repair",
  "Diagnostic Testing",
  "Engine Repair",
  "Transmission Repair",
  "Electrical Systems",
  "Brake Systems",
  "Suspension Systems",
  "Automotive Electronics",
  "Parts Replacement",
  "Vehicle Inspection",
  "Preventive Maintenance",
  "Automotive Engineering",
  "Repair Documentation",
  "Customer Service",
  "Mechanical Troubleshooting",
  "Automotive Diagnostics",
  "Service Scheduling",
  "Automotive Systems",
  "Technical Support",
  "Hospitality Skills",
  "Guest Service",
  "Event Planning",
  "Hotel Management",
  "Food and Beverage Service",
  "Front Desk Operations",
  "Housekeeping Management",
  "Reservations Management",
  "Customer Service",
  "Conflict Resolution",
  "Food Safety",
  "Venue Coordination",
  "Catering Management",
  "Guest Relations",
  "Service Excellence",
  "Hospitality Operations",
  "Travel Planning",
  "Event Coordination",
  "Concierge Services",
  "Tourism Management",
  "Hospitality Marketing",
  "Energy and Utilities Skills",
  "Energy Management",
  "Utilities Management",
  "Renewable Energy",
  "Energy Efficiency",
  "Power Generation",
  "Environmental Compliance",
  "Resource Management",
  "Energy Audits",
  "Grid Management",
  "Energy Procurement",
  "Infrastructure Maintenance",
  "Utility Billing",
  "Sustainable Practices",
  "Energy Conservation",
  "Facility Management",
  "Safety Standards",
  "Process Optimization",
  "Regulatory Compliance",
  "Risk Assessment",
  "Project Management",
  "Real Estate Skills",
  "Property Management",
  "Real Estate Sales",
  "Leasing",
  "Property Valuation",
  "Market Analysis",
  "Client Relations",
  "Negotiation",
  "Investment Analysis",
  "Property Marketing",
  "Real Estate Development",
  "Contract Management",
  "Real Estate Law",
  "Transaction Coordination",
  "Lease Administration",
  "Real Estate Appraisal",
  "Market Research",
  "Property Inspection",
  "Land Acquisition",
  "Real Estate Finance",
  "Portfolio Management",
  "Retail Skills",
  "Merchandising",
  "Customer Service",
  "Sales Strategy",
  "Inventory Management",
  "Visual Merchandising",
  "Store Management",
  "Sales Reporting",
  "Product Knowledge",
  "Retail Marketing",
  "Cash Handling",
  "Loss Prevention",
  "Customer Engagement",
  "Sales Training",
  "Retail Analytics",
  "Store Operations",
  "Stock Control",
  "Display Setup",
  "Customer Feedback",
  "Sales Performance",
  "Vendor Relations",
  "Agriculture Skills",
  "Crop Management",
  "Soil Analysis",
  "Pest Control",
  "Farm Equipment Operation",
  "Irrigation Systems",
  "Agricultural Research",
  "Livestock Management",
  "Harvesting Techniques",
  "Agricultural Engineering",
  "Sustainable Farming",
  "Crop Rotation",
  "Plant Breeding",
  "Agricultural Marketing",
  "Farm Management",
  "Soil Conservation",
  "Organic Farming",
  "Farm Safety",
  "Agricultural Economics",
  "Yield Analysis",
  "Weather Forecasting",
  "Telecommunications Skills",
  "Network Administration",
  "Telecom Systems",
  "Signal Processing",
  "Radio Frequency",
  "Telecommunications Engineering",
  "VoIP Systems",
  "Network Security",
  "Satellite Communications",
  "Telecom Installation",
  "Troubleshooting",
  "Network Design",
  "Data Transmission",
  "Telecommunication Management",
  "Service Provisioning",
  "Telecom Policy",
  "Fiber Optics",
  "Telecom Regulations",
  "Network Optimization",
  "Telecom Support",
  "Infrastructure Management",
  "Legal and Compliance Skills",
  "Regulatory Compliance",
  "Contract Negotiation",
  "Legal Research",
  "Risk Management",
  "Corporate Governance",
  "Compliance Auditing",
  "Legal Documentation",
  "Data Privacy",
  "Policy Development",
  "Ethics Management",
  "Legal Advice",
  "Intellectual Property Rights",
  "Regulatory Reporting",
  "Fraud Prevention",
  "Legal Risk Assessment",
  "Compliance Training",
  "Policy Implementation",
  "Contract Management",
  "Legal Counseling",
  "Governance",
  "Consulting Skills",
  "Advisory Services",
  "Business Strategy",
  "Market Research",
  "Management Consulting",
  "Process Improvement",
  "Organizational Change",
  "Strategic Planning",
  "Business Analysis",
  "Project Management",
  "Client Relationship Management",
  "Problem Solving",
  "Solution Development",
  "Performance Optimization",
  "Risk Assessment",
  "Data Analysis",
  "Financial Consulting",
  "Technology Integration",
  "Change Management",
  "Presentation Skills",
  "Client Needs Assessment",
  "Transportation Skills",
  "Fleet Management",
  "Route Planning",
  "Vehicle Maintenance",
  "Traffic Management",
  "Transportation Logistics",
  "Delivery Coordination",
  "Supply Chain Management",
  "Load Optimization",
  "Transport Safety",
  "Shipping Coordination",
  "Freight Management",
  "Transportation Regulations",
  "Cargo Handling",
  "Transportation Planning",
  "Vehicle Scheduling",
  "Driver Management",
  "Logistics Coordination",
  "Fleet Operations",
  "Inventory Management",
  "Cost Management",
  "Manufacturing and Production Skills",
  "Quality Assurance",
  "Production Planning",
  "Process Engineering",
  "Lean Manufacturing",
  "Assembly Line Management",
  "Production Scheduling",
  "Equipment Maintenance",
  "Manufacturing Processes",
  "Supply Chain Coordination",
  "Process Improvement",
  "Safety Compliance",
  "Materials Handling",
  "Production Efficiency",
  "Cost Reduction",
  "Workflow Optimization",
  "Inventory Control",
  "Quality Control",
  "Prototyping",
  "Industrial Automation",
  "Product Testing",
  "Supply Chain Skills",
  "Procurement",
  "Logistics Coordination",
  "Inventory Management",
  "Supplier Relations",
  "Demand Forecasting",
  "Order Fulfillment",
  "Distribution Management",
  "Warehouse Management",
  "Supply Chain Optimization",
  "Risk Management",
  "Supply Chain Analytics",
  "Vendor Management",
  "Transportation Management",
  "Cost Control",
  "Supply Chain Strategy",
  "Shipment Tracking",
  "Resource Planning",
  "Supplier Evaluation",
  "Supply Chain Integration",
  "Process Improvement",
  "Procurement Skills",
  "Supplier Negotiation",
  "Contract Management",
  "Sourcing Strategies",
  "Purchase Order Management",
  "Supplier Relationship Management",
  "Cost Analysis",
  "Market Research",
  "Vendor Selection",
  "Procurement Strategy",
  "Inventory Control",
  "Purchase Agreements",
  "Supplier Evaluation",
  "Bid Analysis",
  "Procurement Compliance",
  "Supplier Performance Monitoring",
  "Procurement Analytics",
  "Spend Analysis",
  "Strategic Sourcing",
  "Risk Management",
  "Procurement Operations",
  "Training and Development Skills",
  "Curriculum Design",
  "Instructional Design",
  "Training Delivery",
  "Learning Management Systems (LMS)",
  "Employee Development",
  "Training Needs Analysis",
  "Workshop Facilitation",
  "E-learning Development",
  "Skills Assessment",
  "Performance Improvement",
  "Training Program Evaluation",
  "Onboarding",
  "Coaching",
  "Learning Pathways",
  "Training Materials Development",
  "Adult Learning Principles",
  "Leadership Training",
  "Compliance Training",
  "Professional Development",
  "Training Metrics",
  "Leadership Skills",
  "Team Leadership",
  "Visionary Thinking",
  "Decision Making",
  "Strategic Planning",
  "Motivational Skills",
  "Conflict Resolution",
  "Change Management",
  "Goal Setting",
  "Delegation",
  "Emotional Intelligence",
  "Influence and Persuasion",
  "Performance Management",
  "Crisis Management",
  "Team Building",
  "Communication",
  "Negotiation",
  "Problem Solving",
  "Organizational Development",
  "Mentoring",
  "Leadership Development",
  "Organizational Skills",
  "Project Coordination",
  "Time Management",
  "Task Prioritization",
  "Workflow Optimization",
  "Resource Allocation",
  "Scheduling",
  "Event Planning",
  "Documentation Management",
  "Office Management",
  "Budget Management",
  "Meeting Coordination",
  "File Organization",
  "Process Improvement",
  "Strategic Planning",
  "Goal Setting",
  "Risk Management",
  "Record Keeping",
  "Inventory Management",
  "Process Documentation",
  "Team Coordination",
  "Digital Marketing Skills",
  "SEO Optimization",
  "Content Marketing",
  "Social Media Management",
  "PPC Advertising",
  "Email Campaigns",
  "Analytics and Reporting",
  "Digital Strategy",
  "Brand Management",
  "Conversion Rate Optimization",
  "Influencer Marketing",
  "Affiliate Marketing",
  "Marketing Automation",
  "E-commerce Strategies",
  "Content Creation",
  "Audience Targeting",
  "Mobile Marketing",
  "A/B Testing",
  "Customer Acquisition",
  "Digital Advertising",
  "Market Research",
  "Financial Management Skills",
  "Budgeting",
  "Financial Planning",
  "Financial Reporting",
  "Investment Analysis",
  "Cash Flow Management",
  "Risk Management",
  "Cost Control",
  "Financial Forecasting",
  "Profitability Analysis",
  "Accounting Principles",
  "Asset Management",
  "Revenue Analysis",
  "Tax Planning",
  "Financial Modeling",
  "Credit Management",
  "Expense Tracking",
  "Financial Analysis",
  "Investment Strategy",
  "Payroll Management",
  "Debt Management",
  "Risk Management Skills",
  "Risk Assessment",
  "Risk Mitigation",
  "Compliance",
  "Crisis Management",
  "Risk Analysis",
  "Contingency Planning",
  "Loss Prevention",
  "Security Management",
  "Risk Monitoring",
  "Risk Evaluation",
  "Incident Response",
  "Insurance Management",
  "Safety Protocols",
  "Regulatory Compliance",
  "Risk Reporting",
  "Threat Analysis",
  "Risk Control Strategies",
  "Risk Communication",
  "Vulnerability Assessment",
  "Risk Management Strategy",
  "Software Development Skills",
  "Programming Languages",
  "Software Design",
  "Debugging",
  "Software Testing",
  "Application Development",
  "Version Control",
  "Agile Methodology",
  "Software Architecture",
  "Code Review",
  "API Development",
  "Web Development",
  "Mobile Development",
  "Database Integration",
  "User Interface Design",
  "Software Documentation",
  "Continuous Integration",
  "Systems Analysis",
  "Front-end Development",
  "Back-end Development",
  "DevOps Practices",
  "Operations Skills",
  "Operational Planning",
  "Process Optimization",
  "Supply Chain Management",
  "Quality Control",
  "Facility Management",
  "Workflow Management",
  "Resource Management",
  "Budget Management",
  "Performance Metrics",
  "Risk Management",
  "Production Scheduling",
  "Inventory Management",
  "Vendor Management",
  "Logistics Coordination",
  "Cost Reduction",
  "Process Improvement",
  "Safety Compliance",
  "Strategic Planning",
  "Operational Efficiency",
  "Business Operations",
  "Sales and Marketing Skills",
  "Market Research",
  "Sales Strategy",
  "Brand Development",
  "Lead Generation",
  "Customer Acquisition",
  "Sales Negotiation",
  "Campaign Management",
  "Digital Advertising",
  "Content Strategy",
  "Public Relations",
  "Market Analysis",
  "Sales Forecasting",
  "Email Marketing",
  "Product Launch",
  "Social Media Strategy",
  "Event Marketing",
  "Customer Insights",
  "Sales Training",
  "Brand Management",
  "Marketing Analytics",
  "Personal Development Skills",
  "Time Management",
  "Goal Setting",
  "Stress Management",
  "Communication Skills",
  "Emotional Intelligence",
  "Problem-Solving",
  "Decision Making",
  "Self-Motivation",
  "Adaptability",
  "Critical Thinking",
  "Work-Life Balance",
  "Resilience",
  "Leadership Skills",
  "Networking",
  "Professional Growth",
  "Personal Branding",
  "Mindfulness",
  "Self-Discipline",
  "Confidence Building",
  "Conflict Resolution",
  "Project Management Skills",
  "Project Planning",
  "Risk Management",
  "Budgeting",
  "Scheduling",
  "Stakeholder Management",
  "Resource Allocation",
  "Quality Assurance",
  "Project Execution",
  "Change Management",
  "Team Coordination",
  "Performance Monitoring",
  "Project Documentation",
  "Agile Methodology",
  "Project Scope Management",
  "Issue Resolution",
  "Communication",
  "Project Reporting",
  "Workflow Optimization",
  "Resource Management",
  "Project Closure",
  "Technology Skills",
  "IT Support",
  "Network Administration",
  "Software Development",
  "System Integration",
  "Cloud Computing",
  "Cybersecurity",
  "Data Analysis",
  "Technical Troubleshooting",
  "Systems Administration",
  "Application Management",
  "Database Management",
  "IT Infrastructure",
  "Tech Support",
  "Hardware Maintenance",
  "Software Installation",
  "Technology Implementation",
  "IT Project Management",
  "Data Security",
  "Systems Analysis",
  "Technology Strategy",
  "Administrative Skills",
  "Office Management",
  "Scheduling",
  "Document Management",
  "Communication",
  "Data Entry",
  "Administrative Support",
  "Meeting Coordination",
  "Travel Arrangements",
  "Filing Systems",
  "Executive Assistance",
  "Budget Tracking",
  "Record Keeping",
  "Report Preparation",
  "Customer Service",
  "Event Planning",
  "Correspondence Management",
  "Inventory Management",
  "Administrative Procedures",
  "Workflow Management",
  "Office Supplies Management",
];
let predefinedJobTitles = [
  "Software Engineer",
  "Business Development",
  "Marketing Manager",
  "Financial Analyst",
  "Customer Success Manager",
  "Data Scientist",
  "Operations Specialist",
  "Sales Representative",
  "Content Strategist",
  "UX/UI Designer",
  "HR Coordinator",
  "Legal Counsel",
  "Product Manager",
  "Quality Assurance Engineer",
  "Project Coordinator",
  "IT Support Specialist",
  "Event Planner",
  "Public Relations Coordinator",
  "Supply Chain Analyst",
  "Research Assistant",
  "Graphic Designer",
  "Executive Assistant",
  "Social Media Specialist",
  "Healthcare Administrator",
  "Logistics Coordinator",
  "Machine Learning Engineer",
  "Data Scientist",
  "Backend Developer",
  "Frontend Developer",
  "DevOps Engineer",
  "Data Engineer",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Technical Support Engineer",
  "Software Developer",
  "Systems Analyst",
  "Database Administrator",
  "Cybersecurity Specialist",
  "Cloud Engineer",
  "Mobile App Developer",
  "Network Administrator",
  "IT Support Specialist",
  "Systems Architect",
  "Hardware Engineer",
  "Marketing and Sales",
  "Marketing Specialist",
  "Sales Representative",
  "Social Media Manager",
  "Digital Marketing Manager",
  "SEO Specialist",
  "Content Writer",
  "Copywriter",
  "Public Relations Specialist",
  "Brand Manager",
  "Market Research Analyst",
  "Advertising Manager",
  "Email Marketing Specialist",
  "Telecaller",
  "Customer Success Manager",
  "Account Manager",
  "Business Development Manager",
  "Sales Manager",
  "Lead Generation Specialist",
  "Product Marketing Manager",
  "Affiliate Marketing Manager",
  "Finance and Accounting",
  "Financial Analyst",
  "Accountant",
  "Auditor",
  "Tax Specialist",
  "Financial Planner",
  "Budget Analyst",
  "Credit Analyst",
  "Investment Banker",
  "Loan Officer",
  "Controller",
  "Bookkeeper",
  "Payroll Specialist",
  "Compliance Officer",
  "Risk Manager",
  "Treasury Analyst",
  "Accounts Payable Clerk",
  "Accounts Receivable Clerk",
  "Cost Accountant",
  "Financial Consultant",
  "Investment Analyst",
  "Human Resources",
  "HR Specialist",
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Compensation and Benefits Manager",
  "Training and Development Manager",
  "Employee Relations Specialist",
  "HR Coordinator",
  "Payroll Coordinator",
  "HR Generalist",
  "HR Assistant",
  "Diversity and Inclusion Manager",
  "HR Business Partner",
  "Organizational Development Consultant",
  "Performance Management Specialist",
  "Labor Relations Specialist",
  "Benefits Administrator",
  "HRIS Analyst",
  "Employee Engagement Specialist",
  "Learning and Development Specialist",
  "Healthcare",
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Dentist",
  "Physical Therapist",
  "Occupational Therapist",
  "Speech Therapist",
  "Audiologist",
  "Nutritionist",
  "Dietitian",
  "Personal Trainer",
  "Fitness Instructor",
  "Yoga Instructor",
  "Massage Therapist",
  "Acupuncturist",
  "Chiropractor",
  "Veterinarian",
  "Medical Assistant",
  "Physician Assistant",
  "Clinical Research Coordinator",
  "Radiologic Technologist",
  "Laboratory Technician",
  "EMT/Paramedic",
  "Medical Biller",
  "Medical Coder",
  "Health Information Technician",
  "Medical Transcriptionist",
  "Optometrist",
  "Ophthalmologist",
  "Podiatrist",
  "Psychiatrist",
  "Psychologist",
  "Social Worker",
  "Counselor",
  "Therapist",
  "Anesthesiologist",
  "Surgeon",
  "Pediatrician",
  "Cardiologist",
  "Dermatologist",
  "Education",
  "Teacher",
  "Professor",
  "Tutor",
  "Librarian",
  "School Counselor",
  "Instructional Designer",
  "Curriculum Developer",
  "Education Administrator",
  "Special Education Teacher",
  "Teaching Assistant",
  "Education Consultant",
  "Academic Advisor",
  "Admissions Counselor",
  "Career Counselor",
  "Principal",
  "School Nurse",
  "Educational Psychologist",
  "School Social Worker",
  "ESL Teacher",
  "Substitute Teacher",
  "Creative and Media",
  "Graphic Designer",
  "Illustrator",
  "Photographer",
  "Videographer",
  "Video Editor",
  "Animator",
  "Motion Graphics Designer",
  "Art Director",
  "Creative Director",
  "Copywriter",
  "Content Creator",
  "Journalist",
  "Editor",
  "Proofreader",
  "Author",
  "Screenwriter",
  "Blogger",
  "Social Media Influencer",
  "Podcaster",
  "Radio Host",
  "TV Producer",
  "Video Game Designer",
  "Video Game Developer",
  "Game Tester",
  "Musician",
  "Music Producer",
  "Sound Engineer",
  "Actor",
  "Director",
  "Playwright",
  "Choreographer",
  "Dancer",
  "Makeup Artist",
  "Set Designer",
  "Costume Designer",
  "Fashion Designer",
  "Interior Designer",
  "Event Planner",
  "Event Coordinator",
  "Wedding Planner",
  "Customer Service",
  "Customer Service Representative",
  "Call Center Agent",
  "Technical Support Specialist",
  "Help Desk Technician",
  "Client Services Manager",
  "Customer Support Engineer",
  "Customer Success Specialist",
  "Service Manager",
  "Account Executive",
  "Sales Support Specialist",
  "Customer Experience Manager",
  "Member Services Representative",
  "Community Manager",
  "Client Relationship Manager",
  "Customer Retention Specialist",
  "Call Center Supervisor",
  "Call Center Manager",
  "Technical Account Manager",
  "Customer Operations Manager",
  "Customer Service Trainer",
  "Administration and Operations",
  "Administrative Assistant",
  "Executive Assistant",
  "Office Manager",
  "Receptionist",
  "Data Entry Clerk",
  "File Clerk",
  "Office Clerk",
  "Administrative Coordinator",
  "Operations Manager",
  "Facilities Manager",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Inventory Manager",
  "Warehouse Manager",
  "Project Manager",
  "Program Manager",
  "Business Operations Manager",
  "Fleet Manager",
  "Property Manager",
  "Legal and Compliance",
  "Lawyer",
  "Paralegal",
  "Legal Assistant",
  "Legal Secretary",
  "Compliance Officer",
  "Contract Manager",
  "Corporate Counsel",
  "Litigation Support Specialist",
  "Regulatory Affairs Specialist",
  "Risk Manager",
  "Legal Analyst",
  "Intellectual Property Specialist",
  "Court Reporter",
  "Mediator",
  "Arbitrator",
  "Notary Public",
  "Legal Researcher",
  "Compliance Analyst",
  "Compliance Manager",
  "Environmental Compliance Specialist",
  "Science and Research",
  "Scientist",
  "Research Scientist",
  "Research Assistant",
  "Laboratory Technician",
  "Biologist",
  "Chemist",
  "Physicist",
  "Geologist",
  "Environmental Scientist",
  "Microbiologist",
  "Geneticist",
  "Pharmacologist",
  "Biomedical Engineer",
  "Neuroscientist",
  "Psychologist",
  "Sociologist",
  "Anthropologist",
  "Archaeologist",
  "Statistician",
  "Mathematician",
  "Data Analyst",
  "Data Manager",
  "Epidemiologist",
  "Public Health Specialist",
  "Clinical Research Coordinator",
  "Clinical Trial Manager",
  "Toxicologist",
  "Forensic Scientist",
  "Biostatistician",
  "Agricultural Scientist",
  "Food Scientist",
  "Oceanographer",
  "Meteorologist",
  "Astronomer",
  "Ecologist",
  "Trades and Skilled Labor",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Welder",
  "HVAC Technician",
  "Mechanic",
  "Auto Technician",
  "Machinist",
  "CNC Operator",
  "Forklift Operator",
  "Truck Driver",
  "Heavy Equipment Operator",
  "Construction Worker",
  "General Laborer",
  "Painter",
  "Roofer",
  "Landscaper",
  "Pest Control Technician",
  "Janitor",
  "Housekeeper",
  "Security Guard",
  "Maintenance Worker",
  "Facility Maintenance Technician",
  "Appliance Repair Technician",
  "Building Inspector",
  "Food and Hospitality",
  "Chef",
  "Sous Chef",
  "Line Cook",
  "Pastry Chef",
  "Restaurant Manager",
  "Food and Beverage Manager",
  "Bartender",
  "Barista",
  "Server",
  "Host/Hostess",
  "Dishwasher",
  "Catering Manager",
  "Event Coordinator",
  "Hotel Manager",
  "Front Desk Clerk",
  "Concierge",
  "Housekeeping Supervisor",
  "Bellhop",
  "Travel Agent",
  "Tour Guide",
  "Sommelier",
  "Banquet Manager",
  "Kitchen Manager",
  "Hotel Sales Manager",
  "Reservation Agent",
  "Room Service Attendant",
  "Valet Parking Attendant",
  "Night Auditor",
  "Housekeeping Attendant",
  "Guest Services Manager",
  "Arts and Design",
  "Graphic Designer",
  "Illustrator",
  "Photographer",
  "Videographer",
  "Video Editor",
  "Animator",
  "Motion Graphics Designer",
  "Art Director",
  "Creative Director",
  "Interior Designer",
  "Fashion Designer",
  "Industrial Designer",
  "Set Designer",
  "Exhibit Designer",
  "Floral Designer",
  "Landscape Designer",
  "Textile Designer",
  "Jewelry Designer",
  "Printmaker",
  "Calligrapher",
  "Tattoo Artist",
  "Makeup Artist",
  "Hair Stylist",
  "Barber",
  "Nail Technician",
  "Esthetician",
  "Cosmetologist",
  "Stylist",
  "Art Conservator",
  "Art Handler",
  "Public Sector and Non-Profit",
  "Government Relations Specialist",
  "Policy Analyst",
  "Urban Planner",
  "Community Organizer",
  "Non-Profit Manager",
  "Program Coordinator",
  "Grant Writer",
  "Fundraising Coordinator",
  "Volunteer Coordinator",
  "Social Services Case Manager",
  "Public Health Educator",
  "Emergency Management Specialist",
  "Environmental Health Specialist",
  "Public Information Officer",
  "Public Affairs Specialist",
  "Economic Development Specialist",
  "Legislative Assistant",
  "City Manager",
  "Public Administrator",
  "Human Rights Advocate",
  "Sports and Recreation",
  "Sports Coach",
  "Athletic Trainer",
  "Personal Trainer",
  "Fitness Instructor",
  "Yoga Instructor",
  "Pilates Instructor",
  "Sports Agent",
  "Sports Marketing Manager",
  "Recreation Coordinator",
  "Park Ranger",
  "Lifeguard",
  "Swim Instructor",
  "Golf Instructor",
  "Tennis Coach",
  "Camp Counselor",
  "Outdoor Adventure Guide",
  "Sports Official",
  "Event Coordinator",
  "Strength and Conditioning Coach",
  "Physical Education Teacher",
  "Transport and Logistics",
  "Logistics Coordinator",
  "Supply Chain Manager",
  "Warehouse Manager",
  "Inventory Manager",
  "Truck Driver",
  "Delivery Driver",
  "Courier",
  "Fleet Manager",
  "Shipping and Receiving Clerk",
  "Freight Forwarder",
  "Customs Broker",
  "Logistics Analyst",
  "Distribution Manager",
  "Procurement Specialist",
  "Purchasing Manager",
  "Import/Export Coordinator",
  "Warehouse Associate",
  "Inventory Analyst",
  "Supply Chain Analyst",
  "Logistics Manager",
  "Manufacturing and Production",
  "Production Manager",
  "Manufacturing Engineer",
  "Quality Control Inspector",
  "Assembly Line Worker",
  "Production Worker",
  "Machine Operator",
  "CNC Machinist",
  "Welder",
  "Fabricator",
  "Industrial Engineer",
  "Production Supervisor",
  "Plant Manager",
  "Maintenance Technician",
  "Process Engineer",
  "Tool and Die Maker",
  "Quality Assurance Manager",
  "Operations Manager",
  "Material Handler",
  "Packaging Engineer",
  "Robotics Engineer",
  "Real Estate",
  "Real Estate Agent",
  "Real Estate Broker",
  "Property Manager",
  "Leasing Agent",
  "Real Estate Appraiser",
  "Real Estate Analyst",
  "Real Estate Developer",
  "Title Examiner",
  "Mortgage Broker",
  "Real Estate Attorney",
  "Home Inspector",
  "Real Estate Marketing Specialist",
  "Real Estate Assistant",
  "Escrow Officer",
  "Transaction Coordinator",
  "Commercial Real Estate Agent",
  "Property Management Assistant",
  "Real Estate Office Manager",
  "Leasing Consultant",
  "Real Estate Photographer",
  "Retail and Consumer Services",
  "Retail Sales Associate",
  "Store Manager",
  "Assistant Store Manager",
  "Cashier",
  "Stock Clerk",
  "Merchandiser",
  "Customer Service Associate",
  "Sales Supervisor",
  "Visual Merchandiser",
  "Inventory Specialist",
  "Loss Prevention Specialist",
  "Retail Buyer",
  "E-commerce Specialist",
  "Department Manager",
  "Retail Operations Manager",
  "Retail Analyst",
  "Sales Consultant",
  "Mystery Shopper",
  "Personal Shopper",
  "Gift Wrapper",
  "Telecommunications",
  "Telecommunications Technician",
  "Network Engineer",
  "Systems Administrator",
  "Technical Support Specialist",
  "Field Service Technician",
  "Telecom Sales Representative",
  "Telecom Analyst",
  "Cable Installer",
  "Wireless Technician",
  "VoIP Engineer",
  "Telecommunications Engineer",
  "Network Administrator",
  "Customer Support Representative",
  "Project Manager",
  "Network Architect",
  "Technical Project Manager",
  "Infrastructure Manager",
  "Telecom Consultant",
  "Fiber Optic Technician",
  "NOC Technician",
  "Utilities and Energy",
  "Electrical Engineer",
  "Power Plant Operator",
  "Renewable Energy Technician",
  "Wind Turbine Technician",
  "Solar Panel Installer",
  "Energy Analyst",
  "Environmental Engineer",
  "Utilities Manager",
  "Water Treatment Plant Operator",
  "Wastewater Operator",
  "Environmental Health and Safety Specialist",
  "Energy Consultant",
  "Power System Engineer",
  "Field Service Engineer",
  "Utility Worker",
  "Substation Technician",
  "Grid Operator",
  "Hydrologist",
  "Energy Auditor",
  "Meter Reader",
  "Travel and Tourism",
  "Travel Agent",
  "Tour Guide",
  "Flight Attendant",
  "Airline Pilot",
  "Travel Coordinator",
  "Travel Consultant",
  "Cruise Director",
  "Travel Blogger",
  "Travel Photographer",
  "Destination Wedding Planner",
  "Adventure Travel Guide",
  "Travel Writer",
  "Travel Nurse",
  "Travel Sales Specialist",
  "Hospitality Manager",
  "Concierge",
  "Reservations Agent",
  "Tourism Officer",
  "Cultural Heritage Officer",
  "Holiday Representative",
  "Miscellaneous",
  "Researcher",
  "Consultant",
  "Advisor",
  "Specialist",
  "Manager",
  "Director",
  "Coordinator",
  "Assistant",
  "Officer",
  "Executive",
  "Extended List",
  "Electrician Helper",
  "Cable Splicer",
  "Home Health Aide",
  "Medical Records Technician",
  "Veterinary Technician",
  "Research and Development Manager",
  "Ergonomist",
  "Safety Coordinator",
  "Biotechnologist",
  "Marine Biologist",
  "Marine Engineer",
  "Ocean Engineer",
  "Quality Assurance Tester",
  "Quality Control Analyst",
  "Compliance Analyst",
  "Logistics Specialist",
  "Materials Planner",
  "Production Planner",
  "Procurement Manager",
  "Purchasing Agent",
  "Supply Chain Coordinator",
  "Vendor Manager",
  "Customs Compliance Specialist",
  "Distribution Coordinator",
  "Freight Broker",
  "Fulfillment Associate",
  "Inventory Control Specialist",
  "Shipping Clerk",
  "Warehouse Supervisor",
  "Forklift Driver",
  "Picker/Packer",
  "Operations Coordinator",
  "Production Coordinator",
  "Quality Inspector",
  "Safety Manager",
  "Sanitation Worker",
  "Assembler",
  "Fabricator",
  "Foundry Worker",
  "Tool Maker",
  "Machinist",
  "CNC Programmer",
  "Die Setter",
  "Mold Maker",
  "Production Artist",
  "Packaging Designer",
  "Print Production Manager",
  "Prepress Technician",
  "Press Operator",
  "Binder Operator",
  "Collator Operator",
  "Copy Center Operator",
  "Digital Print Operator",
  "Offset Press Operator",
  "Screen Printer",
  "Wide Format Print Operator",
  "Finishing Technician",
  "Bindery Worker",
  "Die Cutter Operator",
  "Gluer Operator",
  "Folder Operator",
  "Stitcher Operator",
  "Cutter Operator",
  "Packaging Machine Operator",
  "Label Printer",
  "Shipping and Receiving Coordinator",
  "Logistics Assistant",
  "Warehouse Assistant",
  "Storekeeper",
  "Warehouse Worker",
  "Inventory Coordinator",
  "Inventory Control Manager",
  "Logistics Manager",
  "Logistics Coordinator",
  "Transportation Manager",
  "Truck Dispatcher",
  "Fleet Supervisor",
  "Delivery Coordinator",
  "Courier Driver",
  "Bike Courier",
  "Car Courier",
  "Van Driver",
  "Truck Driver",
  "Heavy Truck Driver",
  "Dump Truck Driver",
  "Tanker Driver",
  "Bus Driver",
  "School Bus Driver",
  "Charter Bus Driver",
  "Transit Driver",
  "Shuttle Driver",
  "Delivery Driver",
  "Route Driver",
  "Taxi Driver",
  "Limousine Driver",
  "Ride Share Driver",
  "Chauffeur",
  "Ambulance Driver",
  "Hearse Driver",
  "Pilot",
  "Helicopter Pilot",
  "Commercial Pilot",
  "Flight Instructor",
  "Aircraft Mechanic",
  "Avionics Technician",
  "Air Traffic Controller",
  "Airline Operations Agent",
  "Airline Reservation Agent",
  "Airline Ramp Agent",
  "Airline Baggage Handler",
  "Airline Gate Agent",
  "Airline Ticket Agent",
  "Airline Cargo Agent",
  "Ground Service Equipment Mechanic",
  "Aircraft Fueler",
  "Aircraft Cleaner",
  "Aircraft Deicer",
  "Aircraft Marshaller",
  "Aircraft Dispatcher",
  "Airline Catering Coordinator",
  "Airline Security Agent",
  "Aircraft Loadmaster",
  "Aircraft Structural Technician",
  "Aerospace Engineer",
  "Aerospace Technician",
  "Aerodynamics Engineer",
  "Avionics Engineer",
  "Flight Test Engineer",
  "Aerospace Project Manager",
  "Spacecraft Systems Engineer",
  "Spacecraft Operations Engineer",
  "Spacecraft Propulsion Engineer",
  "Spacecraft Thermal Engineer",
  "Spacecraft Communications Engineer",
  "Spacecraft Navigation Engineer",
  "Spacecraft Control Engineer",
  "Spacecraft Power Engineer",
  "Spacecraft Software Engineer",
  "Spacecraft Systems Analyst",
  "Spacecraft Payload Engineer",
  "Spacecraft Integration Engineer",
  "Spacecraft Assembly Technician",
  "Spacecraft Test Technician",
  "Spacecraft Quality Assurance Engineer",
  "Spacecraft Safety Engineer",
  "Spacecraft Reliability Engineer",
  "Spacecraft Configuration Management Engineer",
  "Spacecraft Logistics Engineer",
  "Spacecraft Maintenance Engineer",
  "Spacecraft Operations Specialist",
  "Spacecraft Command and Control Specialist",
  "Spacecraft Mission Planner",
  "Spacecraft Systems Trainer",
  "Spacecraft Operations Trainer",
  "Spacecraft Communications Trainer",
  "Spacecraft Navigation Trainer",
  "Spacecraft Control Trainer",
  "Spacecraft Power Trainer",
  "Spacecraft Software Trainer",
  "Spacecraft Systems Analyst Trainer",
  "Spacecraft Payload Trainer",
  "Spacecraft Integration Trainer",
  "Spacecraft Assembly Trainer",
  "Spacecraft Test Trainer",
  "Spacecraft Quality Assurance Trainer",
  "Spacecraft Safety Trainer",
  "Spacecraft Reliability Trainer",
  "Spacecraft Configuration Management Trainer",
  "Spacecraft Logistics Trainer",
  "Spacecraft Maintenance Trainer",
  "Spacecraft Operations Support Specialist",
  "Spacecraft Communications Support Specialist",
  "Spacecraft Navigation Support Specialist",
  "Spacecraft Control Support Specialist",
  "Spacecraft Power Support Specialist",
  "Spacecraft Software Support Specialist",
  "Spacecraft Systems Analyst Support Specialist",
  "Spacecraft Payload Support Specialist",
  "Spacecraft Integration Support Specialist",
  "Spacecraft Assembly Support Specialist",
  "Spacecraft Test Support Specialist",
  "Spacecraft Quality Assurance Support Specialist",
  "Spacecraft Safety Support Specialist",
  "Spacecraft Reliability Support Specialist",
  "Spacecraft Configuration Management Support Specialist",
  "Spacecraft Logistics Support Specialist",
  "Spacecraft Maintenance Support Specialist",
  "Spacecraft Operations Support Engineer",
  "Spacecraft Communications Support Engineer",
  "Spacecraft Navigation Support Engineer",
  "Spacecraft Control Support Engineer",
  "Spacecraft Power Support Engineer",
  "Spacecraft Software Support Engineer",
  "Spacecraft Systems Analyst Support Engineer",
  "Spacecraft Payload Support Engineer",
  "Spacecraft Integration Support Engineer",
  "Spacecraft Assembly Support Engineer",
  "Spacecraft Test Support Engineer",
  "Spacecraft Quality Assurance Support Engineer",
  "Spacecraft Safety Support Engineer",
  "Spacecraft Reliability Support Engineer",
  "Spacecraft Configuration Management Support Engineer",
  "Spacecraft Logistics Support Engineer",
  "Spacecraft Maintenance Support Engineer",
  "Spacecraft Operations Supervisor",
  "Spacecraft Communications Supervisor",
  "Spacecraft Navigation Supervisor",
  "Spacecraft Control Supervisor",
  "Spacecraft Power Supervisor",
  "Spacecraft Software Supervisor",
  "Spacecraft Systems Analyst Supervisor",
  "Spacecraft Payload Supervisor",
  "Spacecraft Integration Supervisor",
  "Spacecraft Assembly Supervisor",
  "Spacecraft Test Supervisor",
  "Spacecraft Quality Assurance Supervisor",
  "Spacecraft Safety Supervisor",
  "Spacecraft Reliability Supervisor",
  "Spacecraft Configuration Management Supervisor",
  "Spacecraft Logistics Supervisor",
  "Spacecraft Maintenance Supervisor",
  "Spacecraft Operations Manager",
  "Spacecraft Communications Manager",
  "Spacecraft Navigation Manager",
  "Spacecraft Control Manager",
  "Spacecraft Power Manager",
  "Spacecraft Software Manager",
  "Spacecraft Systems Analyst Manager",
  "Spacecraft Payload Manager",
  "Spacecraft Integration Manager",
  "Spacecraft Assembly Manager",
  "Spacecraft Test Manager",
  "Spacecraft Quality Assurance Manager",
  "Spacecraft Safety Manager",
  "Spacecraft Reliability Manager",
  "Spacecraft Configuration Management Manager",
  "Spacecraft Logistics Manager",
  "Spacecraft Maintenance Manager",
  "Spacecraft Program Manager",
  "Spacecraft Project Manager",
  "Spacecraft Operations Director",
  "Spacecraft Communications Director",
  "Spacecraft Navigation Director",
  "Spacecraft Control Director",
  "Spacecraft Power Director",
  "Spacecraft Software Director",
  "Spacecraft Systems Analyst Director",
  "Spacecraft Payload Director",
  "Spacecraft Integration Director",
  "Spacecraft Assembly Director",
  "Spacecraft Test Director",
  "Spacecraft Quality Assurance Director",
  "Spacecraft Safety Director",
  "Spacecraft Reliability Director",
  "Spacecraft Configuration Management Director",
  "Spacecraft Logistics Director",
  "Spacecraft Maintenance Director",
  "Spacecraft Program Director",
  "Spacecraft Project Director",
  "Spacecraft Operations Executive",
  "Spacecraft Communications Executive",
  "Spacecraft Navigation Executive",
  "Spacecraft Control Executive",
  "Spacecraft Power Executive",
  "Spacecraft Software Executive",
  "Spacecraft Systems Analyst Executive",
  "Spacecraft Payload Executive",
  "Spacecraft Integration Executive",
  "Spacecraft Assembly Executive",
  "Spacecraft Test Executive",
  "Spacecraft Quality Assurance Executive",
  "Spacecraft Safety Executive",
  "Spacecraft Reliability Executive",
  "Spacecraft Configuration Management Executive",
  "Spacecraft Logistics Executive",
  "Spacecraft Maintenance Executive",
  "Spacecraft Program Executive",
  "Spacecraft Project Executive",
  "Aerospace Systems Engineer",
  "Aerospace Systems Analyst",
  "Aerospace Systems Architect",
  "Aerospace Systems Designer",
  "Aerospace Systems Developer",
  "Aerospace Systems Engineer II",
  "Aerospace Systems Engineer III",
  "Aerospace Systems Engineer IV",
  "Aerospace Systems Engineer V",
  "Aerospace Systems Lead",
  "Aerospace Systems Manager",
  "Aerospace Systems Director",
  "Aerospace Systems Executive",
  "Aerospace Systems Specialist",
  "Aerospace Systems Consultant",
  "Aerospace Systems Trainer",
  "Aerospace Systems Instructor",
  "Aerospace Systems Support Specialist",
  "Aerospace Systems Support Engineer",
  "Aerospace Systems Supervisor",
  "Aerospace Systems Administrator",
  "Aerospace Systems Coordinator",
  "Aerospace Systems Analyst II",
  "Aerospace Systems Analyst III",
  "Aerospace Systems Analyst IV",
  "Aerospace Systems Analyst V",
  "Aerospace Systems Architect II",
  "Aerospace Systems Architect III",
  "Aerospace Systems Architect IV",
  "Aerospace Systems Architect V",
  "Aerospace Systems Designer II",
  "Aerospace Systems Designer III",
  "Aerospace Systems Designer IV",
  "Aerospace Systems Designer V",
  "Aerospace Systems Developer II",
  "Aerospace Systems Developer III",
  "Aerospace Systems Developer IV",
  "Aerospace Systems Developer V",
  "Aerospace Systems Lead II",
  "Aerospace Systems Lead III",
  "Aerospace Systems Lead IV",
  "Aerospace Systems Lead V",
  "Aerospace Systems Manager II",
  "Aerospace Systems Manager III",
  "Aerospace Systems Manager IV",
  "Aerospace Systems Manager V",
  "Aerospace Systems Director II",
  "Aerospace Systems Director III",
  "Aerospace Systems Director IV",
  "Aerospace Systems Director V",
  "Aerospace Systems Executive II",
  "Aerospace Systems Executive III",
  "Aerospace Systems Executive IV",
  "Aerospace Systems Executive V",
  "Aerospace Systems Specialist II",
  "Aerospace Systems Specialist III",
  "Aerospace Systems Specialist IV",
  "Aerospace Systems Specialist V",
  "Aerospace Systems Consultant II",
  "Aerospace Systems Consultant III",
  "Aerospace Systems Consultant IV",
  "Aerospace Systems Consultant V",
  "Aerospace Systems Trainer II",
  "Aerospace Systems Trainer III",
  "Aerospace Systems Trainer IV",
  "Aerospace Systems Trainer V",
  "Aerospace Systems Instructor II",
  "Aerospace Systems Instructor III",
  "Aerospace Systems Instructor IV",
  "Aerospace Systems Instructor V",
  "Aerospace Systems Support Specialist II",
  "Aerospace Systems Support Specialist III",
  "Aerospace Systems Support Specialist IV",
  "Aerospace Systems Support Specialist V",
  "Aerospace Systems Support Engineer II",
  "Aerospace Systems Support Engineer III",
  "Aerospace Systems Support Engineer IV",
  "Aerospace Systems Support Engineer V",
  "Aerospace Systems Supervisor II",
  "Aerospace Systems Supervisor III",
  "Aerospace Systems Supervisor IV",
  "Aerospace Systems Supervisor V",
  "Aerospace Systems Administrator II",
  "Aerospace Systems Administrator III",
  "Aerospace Systems Administrator IV",
  "Aerospace Systems Administrator V",
  "Aerospace Systems Coordinator II",
  "Aerospace Systems Coordinator III",
  "Aerospace Systems Coordinator IV",
  "Aerospace Systems Coordinator V",
  "Aerospace Systems Analyst VI",
  "Aerospace Systems Analyst VII",
  "Aerospace Systems Architect VI",
  "Aerospace Systems Architect VII",
  "Aerospace Systems Designer VI",
  "Aerospace Systems Designer VII",
  "Aerospace Systems Developer VI",
  "Aerospace Systems Developer VII",
  "Aerospace Systems Lead VI",
  "Aerospace Systems Lead VII",
  "Aerospace Systems Manager VI",
  "Aerospace Systems Manager VII",
  "Aerospace Systems Director VI",
  "Aerospace Systems Director VII",
  "Aerospace Systems Executive VI",
  "Aerospace Systems Executive VII",
  "Aerospace Systems Specialist VI",
  "Aerospace Systems Specialist VII",
  "Aerospace Systems Consultant VI",
  "Aerospace Systems Consultant VII",
  "Aerospace Systems Trainer VI",
  "Aerospace Systems Trainer VII",
  "Aerospace Systems Instructor VI",
  "Aerospace Systems Instructor VII",
  "Aerospace Systems Support Specialist VI",
  "Aerospace Systems Support Specialist VII",
  "Aerospace Systems Support Engineer VI",
  "Aerospace Systems Support Engineer VII",
  "Aerospace Systems Supervisor VI",
  "Aerospace Systems Supervisor VII",
  "Aerospace Systems Administrator VI",
  "Aerospace Systems Administrator VII",
  "Aerospace Systems Coordinator VI",
  "Aerospace Systems Coordinator VII",
  "Aerospace Systems Analyst VIII",
  "Aerospace Systems Analyst IX",
  "Aerospace Systems Architect VIII",
  "Aerospace Systems Architect IX",
  "Aerospace Systems Designer VIII",
  "Aerospace Systems Designer IX",
  "Aerospace Systems Developer VIII",
  "Aerospace Systems Developer IX",
  "Aerospace Systems Lead VIII",
  "Aerospace Systems Lead IX",
  "Aerospace Systems Manager VIII",
  "Aerospace Systems Manager IX",
  "Aerospace Systems Director VIII",
  "Aerospace Systems Director IX",
  "Aerospace Systems Executive VIII",
  "Aerospace Systems Executive IX",
  "Aerospace Systems Specialist VIII",
  "Aerospace Systems Specialist IX",
  "Aerospace Systems Consultant VIII",
  "Aerospace Systems Consultant IX",
  "Aerospace Systems Trainer VIII",
  "Aerospace Systems Trainer IX",
  "Aerospace Systems Instructor VIII",
  "Aerospace Systems Instructor IX",
  "Aerospace Systems Support Specialist VIII",
  "Aerospace Systems Support Specialist IX",
  "Aerospace Systems Support Engineer VIII",
  "Aerospace Systems Support Engineer IX",
  "Aerospace Systems Supervisor VIII",
  "Aerospace Systems Supervisor IX",
  "Aerospace Systems Administrator VIII",
  "Aerospace Systems Administrator IX",
  "Aerospace Systems Coordinator VIII",
  "Aerospace Systems Coordinator IX",
  "Aerospace Systems Analyst X",
  "Aerospace Systems Architect X",
  "Aerospace Systems Designer X",
  "Aerospace Systems Developer X",
  "Aerospace Systems Lead X",
  "Aerospace Systems Manager X",
  "Aerospace Systems Director X",
  "Aerospace Systems Executive X",
  "Aerospace Systems Specialist X",
  "Aerospace Systems Consultant X",
  "Aerospace Systems Trainer X",
  "Aerospace Systems Instructor X",
  "Aerospace Systems Support Specialist X",
  "Aerospace Systems Support Engineer X",
];
let predefinedLocations = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Surat",
  "Jaipur",
  "Chandigarh",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Bhopal",
  "Patna",
  "Vadodara",
  "Ludhiana",
  "Agra",
  "Varanasi",
  "Coimbatore",
  "Visakhapatnam",
  "Madurai",
  "Mysore",
  "Aurangabad",
  "Raipur",
  "Ranchi",
  "Jabalpur",
  "Amritsar",
  "Thane",
  "Ghaziabad",
  "Faridabad",
  "Meerut",
  "Dehradun",
  "Srinagar",
  "Udaipur",
  "Mangalore",
  "Jodhpur",
  "Bikaner",
  "Siliguri",
  "Hubli",
  "Salem",
  "Trivandrum",
  "Kakinada",
  "Erode",
  "Tiruchirappalli",
  "Dhanbad",
  "Jamshedpur",
  "Shillong",
  "Bhubaneswar",
  "Gwalior",
  "Kolkata",
  "Noida",
  "Bhilai",
  "Jammu",
  "Pondicherry",
  "Rourkela",
  "Chennai",
  "Tirupati",
  "Nashik",
  "Kochi",
  "Gurgaon",
  "Navi Mumbai",
  "Warangal",
  "Kolar",
  "Rajkot",
  "Guntur",
  "Durgapur",
  "Bilaspur",
  "Kurnool",
  "Agartala",
  "Jabalpur",
  "Kakinada",
  "Haldia",
  "Jodhpur",
  "Muzaffarpur",
  "Muzzafarpur",
  "Sangli",
  "Akola",
  "Satara",
  "Rishikesh",
  "Amravati",
  "Tirunelveli",
  "Kangra",
  "Rajasthan",
  "Chandrapur",
  "Sonipat",
  "Hoshiarpur",
  "Dharwad",
  "Sonamarg",
  "Jaisalmer",
  "Chittoor",
  "Jhansi",
  "Palakkad",
  "Pali",
  "Kollam",
  "Thane",
  "Bhubaneshwar",
  "Sagar",
  "Kadapa",
  "Nanded",
  "Gaya",
  "Raigarh",
  "Tiruvannamalai",
  "Bardhaman",
  "Haldwani",
  "Mandi",
  "Wokha",
  "Koraput",
  "Gulbarga",
];

module.exports = { predefinedJobTitles, predefinedLocations, predefinedSkills };
